build: off
clone_depth: 5
platform: x64
configuration: Release

environment:
    PKG_NAME: glimix_core
    PYTHON: "C:\\Python36-x64"
    ARCH: x64

install:
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/limix/liknorm/master/install.bat', 'install-liknorm.bat')" && install-liknorm.bat
    - set PATH=%programfiles%\liknorm\bin;%PATH%
    - set LIBRARY_INC=%programfiles%\liknorm\include;%LIBRARY_INC%
    - set LIBRARY_LIB=%programfiles%\liknorm\lib;%LIBRARY_LIB%
    - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
    - python -m pip install https://download.lfd.uci.edu/pythonlibs/j1ulh5xc/numpy-1.14.5+mkl-cp36-cp36m-win_amd64.whl
    - python -m pip install https://download.lfd.uci.edu/pythonlibs/j1ulh5xc/scipy-1.1.0-cp36-cp36m-win_amd64.whl

build_script:
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/ci/master/appveyor.bat', 'appveyor.bat')" && appveyor.bat
