language: python
python: 3.6
env:
  global:
  - PKG_NAME=glimix_core
  - CIBW_SKIP="cp27-* cp34-* cp35-*"
  - CIBW_BEFORE_BUILD_LINUX="./before-build-linux"
matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx
      language: generic
      before_install:
        - brew update
        - brew outdated python || brew upgrade python
        - brew unlink python && brew link python
        - export PATH="/usr/local/opt/python/libexec/bin:$PATH"
        - hash -r
        - pip install --upgrade pip setuptools wheel
addons:
  apt:
    packages:
    - libffi-dev
    - libffi6
script:
- |
  if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
    sudo mkdir -p /usr/local/man
    sudo chown -R "${USER}:admin" /usr/local/man
  fi
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
- |
  if [ "${TRAVIS_TAG:-}" != "" ]; then
    pip install cibuildwheel>=0.9.1
    cibuildwheel --output-dir wheelhouse
    pip install twine
    python -m twine upload --skip-existing wheelhouse/*
  fi
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: lf2EXbgNYVewF+wUxA2M0Vfoe902bYOkV0wrDtDOB6UXQIwGW0ZEtl2X9i69e6PXfYBYt8KHNISD7peYFr7/tvT6B64WqyOv5ONEuVACDsy1MGSLAxYnCXTiHQeBzE72IwijbW1sKajcJssj8R/lUPHXgS6Cqm1sJVGLcDCFfj0Q2wWt0whk8Atp9meS90K3ary80vIal79H+iZ8mAS7aj6Za2TIT2p9zo4eOzfeU3U81BEfQ9m1rgXqHKgPnHQ+uLcTdbHsVu2aoGZDKa6NKwgw8yBXnSNCMhKFC2noGq3ziHEf84JvICCLgRk4a8T3CfF3x6U+zu8iNLSFeV2D8Zg4pLp1LxF2RWOR6pblsuf2s/YLuxqCnhO6m5ENit45wjYul5sjnrvf8wHdYyr+4EpxesgINrp8GkuMTwPEVdRrpjFnX6qep3UK+9e7qRwbwG1zkAg3hqQoAnapop9YcItux5Y8K6HIifV7Z4NX0BJGsGCwfpzSyq0D4NZjL8OFTXL+V7kZQd2bb2283BI4vULn7jNUhf2lMV7XODwd4f6rcXvFuGc+vn+gJ5XQ5MskQeOawYk45m/IULqIsK3Baf6S06E9vilmnM9IDFbcylw7BoKjOH4/KoMdiy8jAaAbRH6OHM9B2klkfvgmkVqO9Uc5blElMTeFE5jm0aenir8=
  on:
    tags: true
    repo: limix/glimix-core
    branch: master
